apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
  labels:
    app: ecommerce-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
        ports:
        - containerPort: {{ index .Values.services "backend" "port" }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}