apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
        ports:
        - containerPort: {{ .Values.services.frontend.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  selector:
    app: frontend
  ports:
  - port: {{ .Values.services.frontend.port }}
    targetPort: {{ .Values.services.frontend.targetPort }}
  type: {{ .Values.services.frontend.type }}